dist: trusty
sudo: false

language: node_js

services:
  - docker
addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - docker build -t bouncing-balls .

deploy:
  provider: script
  script: bash docker_push