dist: trusty
sudo: false

services:
  - docker

install: skip

before_script:
  - docker build -t bouncing-balls-test -f Dockerfile.test .

script:
  - docker run --rm bouncing-balls-test npm run test
  - docker run --rm bouncing-balls-test npm run e2e
  - docker rmi bouncing-balls-test

after_success:
  - docker build -t bouncing-balls .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master