dist: trusty
sudo: false

language: node_js

services:
  - docker
addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

# install:
#   - npm install

install:
  - docker build -t bouncing-balls .
  #- export CHROME_BIN='/usr/bin/google-chrome'

script:
  #- docker run -e CI=true bouncing-balls npm test
  #- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  # - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

deploy:
  provider: script
  script: bash docker_push