dist: trusty
sudo: false

services:
  - docker

install: skip

script:
  - docker build -t bouncing-balls-test -f Dockerfile.test .
  - docker run --rm bouncing-balls-test
  - docker rmi bouncing-balls-test
  - docker build -t bouncing-balls .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master