dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

services:
  - docker

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

before_install:
  - docker build -t bouncing-balls .

deploy:
  provider: script
  script: bash docker_push