FROM node:12-alpine
RUN apk add chromium

WORKDIR /app

ENV CHROME_BIN=/usr/bin/chromium-browser

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install
COPY . .

CMD [ "npm", "run test", "run e2e" ]