FROM node:12-alpine

WORKDIR /app

ENV CHROME_BIN=/usr/bin/chromium-browser

COPY ["package.json", "package-lock.json*", "./"]

RUN apk add chromium
RUN npm install
COPY . .

CMD [ "npm", "run test", "run e2e" ]